FROM apache/kafka:3.7.0

ENV KAFKA_NODE_ID=1
ENV KAFKA_LISTENER_SECURITY_PROTOCOL_MAP='CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
ENV KAFKA_ADVERTISED_LISTENERS='PLAINTEXT_HOST://localhost:9092,PLAINTEXT://yellowdog:19092'
ENV KAFKA_PROCESS_ROLES='broker,controller'
ENV KAFKA_CONTROLLER_QUORUM_VOTERS='1@yellowdog:29093'
ENV KAFKA_LISTENERS='CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
ENV KAFKA_INTER_BROKER_LISTENER_NAME='PLAINTEXT'
ENV KAFKA_CONTROLLER_LISTENER_NAMES='CONTROLLER'
ENV CLUSTER_ID='4L6g3nShT-eMCtK--X86sw'
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
ENV KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
ENV KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
ENV KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
ENV KAFKA_LOG_DIRS='/tmp/kraft-combined-logs'

# RUN echo "done!!"
# RUN echo "$PWD"
# CMD pwd
#RUN ./opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --topic my-topic-1 --replication-factor 1 --partitions 1