version: "3.8"

services:
  kafka:
    # part of the configuration is taken from https://github.com/apache/kafka/blob/trunk/docker/examples/jvm/single-node/plaintext/docker-compose.yml
    # config documentation is here https://github.com/apache/kafka/blob/trunk/docker/examples/README.md#single-node
    image: apache/kafka:3.7.0
    hostname: kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,IN_DOCKER_LISTENER:PLAINTEXT,HOST_LISTENER:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'HOST_LISTENER://localhost:9092,IN_DOCKER_LISTENER://kafka:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,HOST_LISTENER://:9092,IN_DOCKER_LISTENER://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'IN_DOCKER_LISTENER'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
#    healthcheck:
#      # here we might hit 9092 or 19092 as nc just tests for connection, but we use healthcheck to init-topics, hence for consistency use 19092
#      test: nc -z kafka 19092
#      # I was trying to get healthckeck succeed much faster than 30s (that's what we wait for the init-topics to hit now), but didn't succeed
#      timeout: 2s
#      retries: 3
#      interval: 1s

  init-topics:
    image: apache/kafka:3.7.0
    depends_on:
      - kafka
  #      condition: service_healthy
    # NOTE: we're connecting to the HOST_LISTENER listener from within the dockerized network
    command: /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:19092 --create --if-not-exists --topic global-commodity-trade-statistics-raw --replication-factor 1 --partitions 1
    # command: "bash -c while true; do echo . ; sleep 1; done"
